version: '3.4'

services:
  postfix:
    image: catatnight/postfix
    container_name: postfix
    restart: unless-stopped
    tty: true
    ports:
      - '25:25'
  
  db:
    image: mysql:5.7
    container_name: mysql_db
    tty: true
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=xpto
      - MYSQL_USER=xpto
      - MYSQL_PASSWORD=xpto

  postfixadmin:
    image: postfixadmin
    container_name: postfix-admin
    tty: true
    restart: unless-stopped
    volumes:
      - ./volumes/config.local.php:/var/www/html/config.local.php
      - ./volumes/config.inc.php:/var/www/html/config.inc.php
    ports:
      - 8080:80
    environment:
      - POSTFIXADMIN_DB_TYPE=mysqli
      - POSTFIXADMIN_DB_HOST=db
      - POSTFIXADMIN_DB_USER=xpto
      - POSTFIXADMIN_DB_NAME=xpto
      - POSTFIXADMIN_DB_PASSWORD=xpto
    depends_on:
      - db
      - postfix
    